✨ greet message enhancement
iiitv/getmein-web pull request #120
Opened 2020-08-28 16:05 UTC by AmanRaj1608

Fixes #119 

### Description

![image](https://user-images.githubusercontent.com/42104907/91588495-de67a000-e975-11ea-849b-07e1725811f3.png)

### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Non Functional Requirement
- [ ] Follows the code style of this project.
- [ ] Tests Cover Changes
- [ ] I have performed a self-review of my own code
- [ ] All new and existing tests passed.
- [ ] Documentation

2020-08-28 16:21 UTC, yashshah2820 approved these changes

2020-08-28 16:56 UTC, thepushkarp approved these changes
Looks good!

2020-08-29 03:44 UTC, aashutoshrathi requested changes
Wouldn't 📫 icon look better?

2020-08-29 03:44 UTC, aashutoshrathi commented on public/client.js
> +      message: `<span uk-icon='icon: check; ratio: 1.5'></span> <span class=\'uk-text-small\'>Thank You, Check your inbox for the invite.</span>`,
Should we use `uk-icon='icon: mail; ratio: 1.5'`?

2020-08-29 06:43 UTC, AmanRaj1608 commented on public/client.js
> +      message: `<span uk-icon='icon: check; ratio: 1.5'></span> <span class=\'uk-text-small\'>Thank You, Check your inbox for the invite.</span>`,
Yeah it looks better now 

![image](https://user-images.githubusercontent.com/42104907/91630683-00523880-e9f1-11ea-8f99-f76001a445d4.png)

2020-08-29 08:38 UTC, aashutoshrathi approved these changes
LGTM

2020-08-29 08:38 UTC, merged