toggling Issue #85
iiitv/getmein-web pull request #121
Opened 2020-08-28 20:23 UTC by prathmeshkhandelwal1

Fixes #{ISSUE NUMBER}

### Description

_A few sentences describing the change_

###  Screenshot Before Change:
![Screenshot (95)](https://user-images.githubusercontent.com/56167998/91612101-4def8680-e99a-11ea-9bda-d1a81c5f7fbd.png)

### Screenshot After Change:
![Screenshot (96)](https://user-images.githubusercontent.com/56167998/91612111-53e56780-e99a-11ea-8c07-4bbaee39c353.png)

### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Non Functional Requirement
- [x] Follows the code style of this project.
- [x] Tests Cover Changes
- [x] I have performed a self-review of my own code
- [ ] All new and existing tests passed.
- [ ] Documentation

2020-08-29 03:51 UTC, aashutoshrathi commented
@AmanRaj1608 I think requesting review from `iiitv/project-maintainers` is enough.

2020-08-29 03:51 UTC, aashutoshrathi commented
@prathmeshkhandelwal1 Can you give us a test deployment link?

2020-08-29 07:42 UTC, prathmeshkhandelwal1 commented
https://prathmeshkhandelwal1-getmein-web.glitch.me/ @aashutoshrathi

2020-08-29 08:51 UTC, aashutoshrathi requested changes
Have some issues if I start with light theme

![captured](https://user-images.githubusercontent.com/21199234/91633056-e6b9ec80-ea02-11ea-94e1-193f1050f9b8.gif)

2020-08-29 09:52 UTC, prathmeshkhandelwal1 commented
Changes done @aashutoshrathi  deployment -link: https://prathmeshkhandelwal1-getmein-web.glitch.me

2020-08-30 08:27 UTC, prathmeshkhandelwal1 commented
@iiitv/project-maintainers can you plz review it?

2020-08-30 09:45 UTC, aashutoshrathi approved these changes

2020-08-30 09:45 UTC, aashutoshrathi commented
Delete commented code and make sure newline at the end of file

2020-08-30 09:47 UTC, prathmeshkhandelwal1 commented
okk Sir

2020-08-30 09:48 UTC, prathmeshkhandelwal1 commented
Sir what do you mean by new line at the end of file.. i dont get it

2020-08-30 09:51 UTC, thecodepapaya commented on public/darkmode.js
> +// })
@prathmeshkhandelwal1 add a new line character at the end of the file here

2020-08-30 09:51 UTC, prathmeshkhandelwal1 commented
Done Sir @aashutoshrathi

2020-08-30 09:51 UTC, AmanRaj1608 approved these changes
LGTM ✨

2020-08-30 09:51 UTC, thecodepapaya commented on public/dist/darkmode.dev.js
> +// })
@prathmeshkhandelwal1 add a new line character at the end of the file here as well

2020-08-30 09:54 UTC, thecodepapaya approved these changes

2020-08-30 09:54 UTC, thecodepapaya commented on public/darkmode.js
> +// })
Remove code that has been commented out.

2020-08-30 09:57 UTC, merged