added links to contribution guidelines and COC
iiitv/getmein-web pull request #125
Opened 2020-09-24 08:55 UTC by nlok5923

Fixes #54 

### Description
added links to contribution guidelines and code of conduct.

###  Screenshot Before Change:
![Screenshot (1356)](https://user-images.githubusercontent.com/56120084/94123678-f281ae80-fe08-11ea-959f-24437e29ec97.png)

### Screenshot After Change:
![Screenshot (1355)](https://user-images.githubusercontent.com/56120084/94123692-f6adcc00-fe08-11ea-9a9a-0756faa41db3.png)

### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Non Functional Requirement
- [ ] Follows the code style of this project.
- [ ] Tests Cover Changes
- [x] I have performed a self-review of my own code
- [ ] All new and existing tests passed.
- [ ] Documentation

2020-09-24 08:56 UTC, nlok5923 commented
deployment link : https://nlok5923-getmein-web-4.glitch.me/

2020-09-24 12:20 UTC, nlok5923 commented
@iiitv/project-maintainers sir please review this pull request.

2020-09-24 12:23 UTC, aashutoshrathi requested changes

2020-09-24 12:23 UTC, aashutoshrathi commented on views/index.html
> +            </span>
Few changes:
- Add `uk-button` to `anchor tags`
- Wrap both buttons in a div and make it `display: inline` instead of keeping it in a span

2020-09-24 12:23 UTC, aashutoshrathi commented on views/index.html
> +              <a class="uk-text-meta uk-text-center uk-link-reset uk-text-nowrap" target ="_blank" href="https://github.com/iiitv/getmein-web/blob/master/CONTRIBUTING.md">CONTRIBUTION GUIDELINES</a>
`&emsp` is hacky instead use `uk-margin-right-small`

2020-09-24 12:39 UTC, nlok5923 commented
After changes : 
![Screenshot (1357)](https://user-images.githubusercontent.com/56120084/94146116-523b8200-fe28-11ea-8ef5-08a03f64d54c.png)

2020-09-24 12:41 UTC, aashutoshrathi commented
Add `uk-button-default` too. Those should be buttons

2020-09-24 12:47 UTC, nlok5923 commented
After changes  : 
![Screenshot (1358)](https://user-images.githubusercontent.com/56120084/94146914-6f248500-fe29-11ea-90e8-313f22488fa4.png)

2020-09-25 10:51 UTC, nlok5923 commented
deployment  link ; https://nlok5923-getmein-web-5.glitch.me/

2020-09-25 10:59 UTC, aashutoshrathi requested changes
![image](https://user-images.githubusercontent.com/21199234/94259511-316c4d00-ff4c-11ea-8e78-294b17022aab.png)

This is how it will look like after changes

2020-09-25 10:59 UTC, aashutoshrathi commented on views/index.html
> +              <a class="uk-text-meta uk-text-center uk-link-reset uk-button uk-button-default" target ="_blank" href="https://github.com/iiitv/getmein-web/blob/master/CODE_OF_CONDUCT.md"> CODE OF CON
Change classes for both buttons to
```
uk-text-center uk-button uk-button-default uk-border-pill
```

2020-09-25 10:59 UTC, aashutoshrathi commented on public/style.css
> +  display: inline;
Add `margin: 1rem`

2020-09-25 11:20 UTC, nlok5923 commented
@aashutoshrathi sir After changes it looks like : 
![Screenshot (1365)](https://user-images.githubusercontent.com/56120084/94261234-5fb74180-fee6-11ea-818a-58318202ae00.png)

2020-09-25 11:25 UTC, aashutoshrathi commented
Make sure the spacing is correct here

2020-09-25 11:37 UTC, nlok5923 commented
sir on adding spacing those button move over the footer as footer `position : absolute` as well as there no more space for footer to shift below while maintaining `100vh`
![Screenshot (1368)](https://user-images.githubusercontent.com/56120084/94262777-d9502f00-fee8-11ea-8b4f-7854c49835ea.png)

2020-09-26 10:29 UTC, AmanRaj1608 commented
@nlok5923 device size?
I guess this should be fine for all devices 
For device height lower than 650 we have to use media query

2020-09-26 17:02 UTC, nlok5923 commented
> @nlok5923 device size?
> I guess this should be fine for all devices
> For device height lower than 650 we have to use media query
> 
> https://loutish-chain.surge.sh/

Sir but in this too https://loutish-chain.surge.sh/ button overlap with footer in desktop view.

2020-09-26 17:03 UTC, nlok5923 commented
> > @nlok5923 device size?
> > I guess this should be fine for all devices
> > For device height lower than 650 we have to use media query
> > https://loutish-chain.surge.sh/
> 
> Sir but in this implementation too https://loutish-chain.surge.sh/ button overlap with footer in desktop view.
> 
> > **[Welcome to IIITV](https://loutish-chain.surge.sh/)**Portal to get an invite to IIITV Github
> >       organization

2020-09-26 17:19 UTC, yashshah2820 requested changes
![WhatsApp Image 2020-09-26 at 10 47 18 PM](https://user-images.githubusercontent.com/42682370/94346460-64950600-004a-11eb-8803-627a0114da57.jpeg)

In mobile view, there is no space between the to buttons

2020-09-27 00:59 UTC, closed without merging

2020-09-29 18:08 UTC, yashshah2820 commented
@nlok5923 why did you close this PR and opened a new work, try to work on the same PR

2020-09-29 18:12 UTC, nlok5923 commented
@yashshah2820 sorry sir for making a new for for the same issue . But sir there were some issues with my machine with the file location that's why I had to open a new pr.

Sir I will not repeat the same mistake again.