added button to contribution guidelines and COC
iiitv/getmein-web pull request #130
Opened 2020-09-27 01:04 UTC by nlok5923

Fixes #125 

### Description

Added button for contribution guidelines and code of conduct.

###  Screenshot Before Change:
![Screenshot (1376)](https://user-images.githubusercontent.com/56120084/94353175-a14d0700-0022-11eb-9365-a7a5abc08039.png)

### Screenshot After Change:
![Screenshot (1375)](https://user-images.githubusercontent.com/56120084/94353180-a6aa5180-0022-11eb-9ae1-c165eece916b.png)

### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Non Functional Requirement
- [ ] Follows the code style of this project.
- [ ] Tests Cover Changes
- [x] I have performed a self-review of my own code
- [ ] All new and existing tests passed.
- [ ] Documentation

deployment link : https://nlok5923-getmein-web-6.glitch.me/

2020-09-28 09:03 UTC, nlok5923 commented
@iiitv/project-maintainers  please review this pull request.

2020-09-29 18:05 UTC, yashshah2820 requested changes
@nlok5923 add 20px margin between the repo links and the submit button same as that between the span tag and the submit button.

2020-09-30 04:21 UTC, nlok5923 commented
After changes : 
![Screenshot (1389)](https://user-images.githubusercontent.com/56120084/94642668-aa93d900-0299-11eb-97ba-bbec49eecb68.png)

2020-09-30 18:14 UTC, yashshah2820 approved these changes

2020-10-01 04:32 UTC, aashutoshrathi requested changes

2020-10-01 04:32 UTC, aashutoshrathi commented on views/index.html
> +    <footer class="uk-align-center uk-text-center uk-margin-remove">
Are we sure about removing this?
The margins don't look right. The page is also showing a disabled scrollbar and the footer content is being cut due to screen size.

Can we just calmly write some CSS to make sure content fits in 100vh always?

![image](https://user-images.githubusercontent.com/21199234/94768412-03b05980-03cd-11eb-95f1-989d5f107586.png)

2020-10-02 06:26 UTC, nlok5923 commented
@aashutoshrathi  Sir, there isn't much space for buttons while maintaining the same space as it is between the submit button and span element. that's why i has to apply `uk-margin-remove` to the footer div . but sir if we has to keep footer in the same way as before we has to go with this implementation while keeping the page fits in 100vh .


![Screenshot (1401)](https://user-images.githubusercontent.com/56120084/94893880-08acf180-043d-11eb-93fe-47282ee3d83d.png)

 or if we can make page scrollable we can go with buttons.
sir if there any other possible option please let me know.

2020-10-14 15:31 UTC, closed without merging