cors issues fixed and state username color bug fixed
iiitv/getmein-web pull request #132
Opened 2020-10-07 15:16 UTC by prathmeshkhandelwal1

Fixes #127 

### Description

CORS added and bug fixed.

### Screenshot After Change:

![Screenshot (124)](https://user-images.githubusercontent.com/56167998/95350748-23b8af00-08de-11eb-8a86-13ea6353fdc4.png)

### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

### Non Functional Requirement
- [x] Follows the code style of this project.
- [x] I have performed a self-review of my own code
- [x] All new and existing tests passed.

2020-10-08 11:08 UTC, aashutoshrathi requested changes
Also, @iiitv/project-maintainers who added jQuery to this project? 😭

2020-10-08 11:08 UTC, aashutoshrathi commented on public/client.js
> +    const profile = 'https://cors-anywhere.herokuapp.com/https://api.aashutosh.dev/gh/' + username.val()
No need of CORS anywhere here, I have whitelisted `getmein.glitch.me`

2020-10-08 11:08 UTC, aashutoshrathi commented on public/client.js
> +    fetch(`https://cors-anywhere.herokuapp.com/https://api.github.com/search/users?q=${username}`)
Same here

2020-10-08 11:55 UTC, AmanRaj1608 commented
I thought we were using jQuery from the [start](https://github.com/iiitv/getmein-web/blob/1eec74b15f9d34f0b2131e58f70bb64be98f8137/views/index.html). 🤔
However, we can now move from jQuery to vanilla JS.

Also, I was thinking if we can have a new design 😅

2020-10-08 11:58 UTC, aashutoshrathi commented
Oh! Got it. jQuery was added for UIKit but not for us 😟

2020-10-11 18:27 UTC, prathmeshkhandelwal1 commented on public/client.js
> +    const profile = 'https://cors-anywhere.herokuapp.com/https://api.aashutosh.dev/gh/' + username.val()
![Screenshot (137)](https://user-images.githubusercontent.com/56167998/95686732-7ddaac80-0c1d-11eb-95b1-20f7bd7152bf.png)


> No need of CORS anywhere here, I have whitelisted `getmein.glitch.me`

But it is still giving CORS error

2020-10-11 18:28 UTC, prathmeshkhandelwal1 commented on public/client.js
> +    const profile = 'https://cors-anywhere.herokuapp.com/https://api.aashutosh.dev/gh/' + username.val()
I also tried some other URLs but the results were same :(
![Screenshot (135)](https://user-images.githubusercontent.com/56167998/95686755-a662a680-0c1d-11eb-8a66-1162b9026603.png)
![Screenshot (136)](https://user-images.githubusercontent.com/56167998/95686765-b1b5d200-0c1d-11eb-8d53-f240425c0647.png)

2020-10-11 23:49 UTC, aashutoshrathi commented on public/client.js
> +    const profile = 'https://cors-anywhere.herokuapp.com/https://api.aashutosh.dev/gh/' + username.val()
Bro you are testing on localhost, I'm saying I whitelisted GetMeIn.glitch.me

2020-10-11 23:50 UTC, aashutoshrathi requested changes
Check comment

2020-10-13 01:31 UTC, aashutoshrathi commented
How about we move API url to env so that if URL changes we don't have to change in code.

2020-10-14 04:44 UTC, prathmeshkhandelwal1 commented
> How about we move API url to env so that if URL changes we don't have to change in code.

That's a great idea Sir, will implement in text commit today.

2020-10-14 04:47 UTC, aashutoshrathi commented
Also, update this [Table](https://github.com/iiitv/getmein-web#environment-variables) in README

2020-10-14 19:16 UTC, prathmeshkhandelwal1 commented
> Also, update this [Table](https://github.com/iiitv/getmein-web#environment-variables) in README

Sure sir

2020-10-15 06:28 UTC, prathmeshkhandelwal1 commented
> How about we move API url to env so that if URL changes we don't have to change in code.

Sir, as there is jquery in client.js, i am little bit confused about how to do it. i created the env file and also used  `require('dotenv').config()` in client file but it is giving error. i also tried to find soln online but it does'nt help. can you plz help me with this.

2020-10-15 07:52 UTC, aashutoshrathi commented
We are already using env vars at many places in the project, just read and understand the flow there.
Also, what is the error you are getting?

2020-10-15 12:00 UTC, aashutoshrathi requested changes

2020-10-15 12:00 UTC, aashutoshrathi commented on public/client.js
> +    const profile = 'https://api.aashutosh.dev/gh/' + username.val()
Use Template Strings

2020-10-15 12:00 UTC, aashutoshrathi commented on public/client.js
> +        console.log(data)
And remove this log

2020-10-15 17:46 UTC, prathmeshkhandelwal1 commented
> We are already using env vars at many places in the project, just read and understand the flow there.
> Also, what is the error you are getting?

while using `require('dotenv').config()` in client.js ..its giving require is not defined

2020-10-15 17:49 UTC, prathmeshkhandelwal1 commented
Sir i committed rest changes in this commit other than env file.

2020-10-16 03:33 UTC, aashutoshrathi commented
@prathmeshkhandelwal1 Got it, it is client-side JS, so just do the requested changes and I guess we are good to go.

2020-10-16 07:03 UTC, aashutoshrathi commented on public/client.js
> +    const profile = `https://api.aashutosh.dev/gh/` + username.val()
Add the variable in the template string itself.

2020-10-23 16:58 UTC, prathmeshkhandelwal1 commented
@aashutoshrathi Can u review this again?

2020-10-23 17:33 UTC, aashutoshrathi approved these changes
LGTM

2020-10-23 17:33 UTC, aashutoshrathi commented
Will try to deploy and test this tommorow.

2020-10-25 14:08 UTC, aashutoshrathi commented
@iiitv/project-maintainers Can you deploy and check this?

2020-11-03 12:35 UTC, merged