:pencil2: fixed get me in mail sending feature and updated tokens
iiitv/getmein-web pull request #148
Opened 2022-10-01 05:35 UTC by DhruvDave12

Fixed the bug because of which mail weren't being send to the users and removed slack feature

2022-10-01 14:06 UTC, neeraj3029 requested changes

2022-10-01 14:06 UTC, neeraj3029 commented on constants.js
> +exports.selfEmail = 'IIITV Coding Club <davedhruv1201@gmail.com>'
change it to CC's email

2022-10-01 14:06 UTC, neeraj3029 commented on public/client.js
> +        for(let i=0; i<out.total_count; i++){
Can you share a sample response here? Has the response type changed from object to object[] ?

2022-10-01 14:06 UTC, neeraj3029 commented on public/client.js
> +        for(let i=0; i<out.total_count; i++){
Use `Array.filter` to filter out required users and remove all the flag logic

2022-10-01 14:06 UTC, neeraj3029 commented on public/client.js
> +        // if (out.total_count === 1) {
Remove commented code and logs

2022-10-01 14:15 UTC, neeraj3029 commented
Why do we have lockfile changes without `package.json` updates?

2022-10-01 20:20 UTC, aashutoshrathi commented on public/client.js
> +        for(let i=0; i<out.total_count; i++){
yup! seems like that
https://api.github.com/search/users?q=linus

2022-10-01 20:21 UTC, aashutoshrathi commented on public/client.js
> +        for(let i=0; i<out.total_count; i++){
Also, I think in our case, we don't need to iterate, ideally, there should be either 0 or 1 entries in the response.

2022-10-01 20:24 UTC, aashutoshrathi commented on public/client.js
> +        for(let i=0; i<out.total_count; i++){
Wait I'm not even sure if we need search API, I think our use case will be solved using User API
Eg: https://api.github.com/users/aashutoshrathi

2022-10-01 20:26 UTC, aashutoshrathi requested changes
There are some comments by @neeraj3029 that needs to be resolved, plus code-quality is bad in general in this repo, so when you get time let's clean that up too.
Once all that is done, let me know I can provide one of you people the access to Glitch deployment (ideally someone with access to CC Email, since it has details linked to that in env)

2022-10-02 06:55 UTC, DhruvDave12 commented on public/client.js
> +        for(let i=0; i<out.total_count; i++){
okay sir i will update the right now i checked on entering a username an array of object with username in different combination of lowercase and uppercase were coming so i will update the API to get user one

2022-10-02 06:55 UTC, DhruvDave12 commented on public/client.js
> +        for(let i=0; i<out.total_count; i++){
yes sir sure will update the code

2022-10-02 07:51 UTC, DhruvDave12 commented
I have updated the github api to fetch the user directly, removed the comments and unnecessary logs, and also fixed one toast issue that send the message of "Thank you, check your inbox" only if the username exists.

Remaining changes like
1. Updating the CC mail.
2. Putting the credentials of CC.
3. Improving further code quality

This all will be done latest by tomorrow.

2023-03-18 16:20 UTC, Im-Madhur-Gupta approved these changes
LGTM

2023-03-18 16:21 UTC, merged